<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="overview.aspx.cs" Inherits="UMRPublic.overview" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>UMR Holdings International Corp</title>
<meta name="description" content="UMR Holdings International Corp"/>
<meta name="keywords" content="jewelry, watches"/>
<link href="css/style.css" rel="stylesheet" type="text/css">
        <style type="text/css">
            .style1
            {
                font-size: 18px;
                font-weight: normal;
                text-transform: uppercase;
                color: #48555a;
                font-family: "Rod Transparent";
            }
            #page {
  margin-left:auto;
  margin-right:auto;
  width:800px;
}
            </style>
        
        <script language="Javascript">
            var this_date_timestamp = new Date();
            var this_year = this_date_timestamp.getYear();

            if (this_year < 1000)
                this_year += 1900; //fix Y2K problem
            if (this_year == 101)
                this_year = 2001; 	//fix Netscape browsers - it displays the year as being the year 101!

            var this_year_string = this_year;
</script>
</head>

<body>

<div id="page">
    <form id="form1" runat="server">
    
    <table border="0" cellpadding="0" cellspacing="0" width="50%" height="100%" 
        align="center">
  <tr>
<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="1">
        <div style="position:absolute; width:302px; top:30px; background:url(images/m.jpg);">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="1"><img src="images/logo.jpg" alt="" width="61" height="61" class="logo"></td>
    <td class="style1">
        <h3 style="font-family: Arial, Helvetica, sans-serif">
            &nbsp;</h3>
      </td>
  </tr>
</table>
        </div>
        <div id="slogan">
            A leader in Healthcare Information Technology</div>
        <img src="images/p1.jpg" alt="" width="666" height="196"></td>
        <td class="hbg">&nbsp;</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td height="100%" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="188" valign="top">
        <div style="position:relative; top:-47px; width:188px; left: 0px;">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="mbg"><table width="100%" border="0" cellspacing="0" cellpadding="0" 
            style="height: 250px">
      <tr>
        <td><img src="images/spacer.gif" alt="" width="1" height="14"></td>
      </tr>
      <tr>
        <td class="menu"><a href="Default.aspx">Home</a></td>
      </tr>
      <tr>
        <td height="1"><img src="images/m-sep0.gif" width="188" height="1"></td>
      </tr>
      <tr>
        <td class="menu"><a href="AboutUs1.aspx">About Us</a></td>
      </tr>
      <tr>
        <td height="1"><img src="images/m-sep.gif" width="188" height="1"></td>
      </tr>
      <tr>
        <td class="menu"><a href="Products.aspx">Products and Services</a></td>
      </tr>
      <tr>
        <td height="1"><img src="images/m-sep.gif" width="188" height="1"></td>
      </tr>
      <tr>
        <td class="menu"><a href="Client1.aspx">Client Access</a></td>
      </tr>
      <tr>
        <td height="1"><img src="images/m-sep.gif" width="188" height="1"></td>
      </tr>
      <tr>
        <td class="menu"><a href="Contact.aspx">Contact Us</a></td>
      </tr>
      <tr>
        <td height="1"><img src="images/m-sep.gif" width="188" height="1"></td>
      </tr>
      <tr>
        <td class="menu"><a href="Job.aspx">Job Openings</a></td>
      </tr>
      <tr>
        <td height="1"><img src="images/m-sep.gif" width="188" height="1"></td>
      </tr>
      <tr>
        <td class="menu"><a href="References.aspx">References</a></td>
      </tr>
      <tr>
        <td height="1"><img src="images/m-sep.gif" width="188" height="1"></td>
      </tr>
      <tr>
        <td class="menu">....</td>
      </tr>
      <tr>
        <td><img src="images/spacer.gif" alt="" width="1" height="12"></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td align="right" bgcolor="#FFFFFF"><img src="images/m-bottom.gif" alt="" width="156" height="110"></td>
  </tr>
</table>

        </div>
        &nbsp;&nbsp;&nbsp;
                            </td>
        <td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td class="c-sep-bg"><img src="images/w17.gif" alt="" width="17" height="1"></td>
          </tr>
          <tr>
            <td class="body_txt">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td valign="top"><div><P style="TEXT-ALIGN: center" class=defaulttext align=center><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv">UNIVERSAL MEDICAL RECORDS<SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN></B></SPAN></P>
<P style="TEXT-ALIGN: center" class=defaulttext align=center><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv">22 THE CROSS ROAD</SPAN></B></SPAN></P>
<P style="TEXT-ALIGN: center" class=defaulttext align=center><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv">CORTLANDT MANOR, NEW YORK<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>10567</SPAN></B></SPAN></P>
<P style="TEXT-ALIGN: center" class=defaulttext align=center><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv">Tel: (914) 737-7499&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fax: (212) 504-7956</SPAN></B></SPAN></P>
<P class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv">Copyright </SPAN></B></SPAN><B><SPAN style="FONT-FAMILY: Symbol">ã</SPAN></B><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv"> 1996-
<SCRIPT language=JavaScript>document.write(this_year_string);</SCRIPT> Universal Medical Records<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>All rights reserved.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Patents Pending.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Printed in the United States of America.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>No part of this publication may be reproduced in a retrieval system, or transmitted, in any form or by any means, electronic, mechanical, photocopying, recording, or otherwise, without the prior written permission of the company.</SPAN></B></SPAN></P>
<P class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: 'Arial Narrow'; FONT-SIZE: 10pt">Ver 121009</SPAN></B></SPAN></P>
<H2><SPAN style="FONT-FAMILY: Helv; FONT-WEIGHT: normal" class=initialstyle>TABLE OF CONTENT</SPAN></H2>
<P class=defaulttext><SPAN class=initialstyle><B><U><SPAN style="FONT-FAMILY: Helv">SECTION<SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>TITLE<SPAN style="mso-tab-count: 2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</SPAN></SPAN></U></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">1.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt">INTRODUCTION</SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">2.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#OVERVIEW">OVERVIEW</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">3.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial; FONT-SIZE: 10pt"><A href="#VIRTUAL">VIRTUAL MEDICAL NAVIGATOR GATEKEEPER<SPAN style="FONT-WEIGHT: normal"> </SPAN><SPAN style="FONT-FAMILY: Symbol; mso-bidi-font-family: 'Arial Unicode MS'">ä</SPAN><SPAN style="FONT-WEIGHT: normal"> </SPAN>PROGRAM</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">4.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#VIRTUAL">INVESTIGATING AND PREVENTING MANAGED HEALTHCARE FRAUD AND ABUSE</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">5.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#VIRTUAL">FEATURES AND BENEFITS</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">6.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#prod_ben">PRODUCT BENEFITS</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">7.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#employer">EMPLOYER’S WELLNESS TRACKING SYSTEM</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">8.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#payor">BENEFITS TO PAYOR OR INSURER</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">9.<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#employ">BENEFITS TO EMPLOYER</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">10.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#member">BENEFITS TO ENROLLED MEMBER</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">11.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#licensed">BENEFITS TO LICENSED HEALTH CARE PROVIDER OR ROFESSIONAL</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">12.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#government">BENEFITS TO GOVERNMENT</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">13.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#hr">HUMAN RESOURCE COST REDUCTION</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">14.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#samp">UMR SAMPLE RECORD PRINTOUT</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">15.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="#med">MEDICAL RECORD ANALYZER <SPAN style="FONT-FAMILY: Symbol">ä</SPAN> BUREAU</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in">16.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="UMR_Wellness Tracking_System.pdf">UMR WELLNESS TRACKING SYSTEM</A></SPAN></B></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in"><SPAN class=initialstyle>17.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="Doctor_Alert Network.pdf">DOCTOR ALERT NETWORK </SPAN></B></SPAN><B><SPAN style="FONT-FAMILY: Symbol; FONT-SIZE: 10pt">ä</SPAN></B><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"> </SPAN></B></A><O:P></O:P></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l4 level1 lfo12; tab-stops: list .5in"><SPAN class=initialstyle>18.<SPAN style="FONT: 7pt 'Times New Roman'"> </SPAN><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt"><A href="Health_Care Bridge.pdf">HEALTH CARE BRIDGE</A></SPAN></B><O:P> </O:P></SPAN></P>
<P><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 10pt">&nbsp;<O:P> </O:P></SPAN></B></SPAN></P>
<P><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv"><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="mso-spacerun: yes">&nbsp;</SPAN><O:P> </O:P></SPAN></B></SPAN></P><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Helv; FONT-SIZE: 12pt; mso-bidi-font-family: 'Arial Unicode MS'; mso-fareast-font-family: 'Arial Unicode MS'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA"><BR style="PAGE-BREAK-BEFORE: always" clear=all></SPAN></B></SPAN>
<P style="TEXT-ALIGN: center" align=center><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">UMR</SPAN></B></SPAN></P>
<P style="TEXT-ALIGN: center" class=defaulttext align=center><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">Striving For Excellence</SPAN></B></SPAN></P>
<P style="TEXT-ALIGN: center" class=defaulttext align=center><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">Employee Healthcare Information Management</SPAN></B></SPAN></P>
<P class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>&nbsp;</SPAN></P>
<P class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>&nbsp;</SPAN></P>
<H2><SPAN class=initialstyle>OVERVIEW<SPAN style="mso-spacerun: yes">&nbsp;</SPAN></SPAN></H2>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Just as the re-engineering of corporate America’s business practices created a whole new set of information needs and technological applications, so are the broad changes under way in health care creating a demand for new technologies.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Traditionally the most critical medical related document, the patient record, has lived on separate paper forms literally log jamming the abilities of the health care industry to properly manage the employee/patient’s wellness and the costs associated with maintenance/rehabilitation.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Successfully managing care requires better access throughout the system.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Business entities practicing managed care realize that they have to be able to manage information.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>In a recent New Jersey State commissioned $2.0 million dollar study, NJIT stated that the ideal Electronics Data Information (EDI) medical management system would be able to deliver the following features:</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l7 level1 lfo3; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Paperless Medical Information Systems</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l7 level1 lfo3; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>On-line Access to Medical Records</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l7 level1 lfo3; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Total Quality Management</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l7 level1 lfo3; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Informed Consumers - Employee and Payor</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l7 level1 lfo3; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Managed Care with or without HMO’s<SPAN style="mso-spacerun: yes">&nbsp;</SPAN></SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>NJIT’s conceptual system of the future is available <U>now</U> from Universal Medical Records.</SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Universal Medical Records (UMR) has been engaged in research and development efforts involving automated data records and medical/health care since 1996.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Its primary focus has been the implementation of an integrated computerized patient medical record and the services associated with it for offering immediate and cost-effective on-line worldwide storage, access and retrieval</SPAN><SPAN style="FONT-FAMILY: Helv" class=initialstyle>.</SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Helv" class=initialstyle>The basics for this concept were developed by Dr. Steven Cohn (see curriculum vitae) over the past ten years.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The format and organization of this record is in compliance with the standards recommended by the American Society of Testing and Materials (ASTM).<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The data content also complies with federal requirements for confidential medical data<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>records under the American with Disability Act (ADA) that must be met by all companies with 15 or more employees.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This act stipulates that the medical condition or history of the employee “shall be collected and maintained on separate forms and in separate medical files and be treated as a confidential medical record.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The requirement is <U>not</U> limited to disabled individuals, it applies to <U>all</U> employees and failure to comply could subject the employer to citations and applicable fines.</SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Helv" class=initialstyle>Accordingly, UMR is positioned to offer an electronic medical records management system that delivers.</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Confidentiality</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Health and Wellness Education Support</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Ease of Use - No Training Necessary</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Paperless Records and Retrieval System</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Interfaces with <U>Existing</U> <U>Equipment</U>, <U>Forms</U>, and <U>Protocol</U></SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Organized Case Management and Billing Management Systems</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Employee/Employer Benefits</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Universal Applications - WCIS and HRIS</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Helv" class=initialstyle>Expandability and Portability</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>MEASURABLE COST CONTAINMENT</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l0 level1 lfo2; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>HUMAN RESOURCE COST REDUCTION</SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>&nbsp;</SPAN></P>
<H2><A name=OVERVIEW></A><A name=VIRTUAL><SPAN style="mso-bookmark: OVERVIEW" class=initialstyle>VIRTUAL MEDICAL NAVIGATOR GATEKEEPER </SPAN></A><SPAN style="mso-bookmark: OVERVIEW" class=initialstyle><SPAN style="FONT-FAMILY: Symbol; mso-char-type: symbol; mso-symbol-font-family: Symbol; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">Ô</SPAN> PROGRAM</SPAN></H2>
<P style="TEXT-ALIGN: center" class=defaulttext align=center><SPAN style="FONT-FAMILY: Arial" class=initialstyle>&nbsp;</SPAN></P>
<P class=MsoBodyText><SPAN style="FONT-FAMILY: Arial">Universal Medical Records (UMR) is an organization that has been engaged in the research and development efforts involving automated data records and medical /<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>healthcare since 1996.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Its primary focus has been the implementation of an integrated computerized patient medical record and the services associated with this medical record for offering immediate and cost-effective on-line worldwide storage, access and retrieval.<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">The basis for this concept was developed over the past twelve years.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The format and organization of this medical record is in compliance with the standards recommended by the American Society of Testing and Materials (ASTM).<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The data content also complies with federal requirements for confidential medical data records under the American with Disability Act (ADA), a standard that must be met by all companies with 15 or more employees.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This act stipulates that the medical condition or history of the employee “shall be collected and maintained on separate forms and in separate medical files and be treated as a confidential medical record”.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This requirement is not limited to disabled individuals, it applies to all employees and failure to comply could subject the employer to citations and applicable fines.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Furthermore, HIPAA regulations require medical information to be transmitted securely, stored securely, transactionally secured with all medical information being accessible by the patient.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR with a partnership with Web/MD provides the tools for HIPAA compliance today.<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">UMR has developed the world's most sophisticated and intelligent integrated healthcare delivery system that addresses managed care in any healthcare setting.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The system is centralized around a proprietary database of ICD-9 codes, CPT-4 Codes, NDC and HCPCS Codes, and telecommunication products and services.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR has concentrated its resources on finding the solution to creating a virtual Community Health Information System, that allows the patient to enter any healthcare system, obtain the appropriate information and receive the proper care according to their own Universal Medical Record.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">Today, when the patient enters a healthcare provider's setting, the patient must recall past events, which may or may not be recalled correctly, but the process is also time consuming, redundant and may be malpractice and error prone.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>When the patient leaves the healthcare setting, he or she does not receive a receipt of services in an intelligent format that can be utilized again the next time a healthcare encounter occurs.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This is the healthcare dilemma!<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>In addition, how would another healthcare provider know what the previous healthcare encounter was and whether or not the patient received proper follow-up care from a previous provider?<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This inability to clearly know, allows for complete incontinuity of healthcare and makes no provision for "Checks and Balances" between providers, patients and payors.<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">The healthcare delivery system is currently structured so that when an individual enters the system a history is created.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This process is known as “Review of Systems”.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR has developed a mechanism of automating this process [Patents Pending].<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The next patient episode is the actual physical examination that also pertains to the Review of Systems and most importantly focuses on the "Chief Complaint".<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The results from this encounter are then entered into the provider’s Healthcare Clinical System (this can be anything from a completely manual paper system to a sophisticated electronic medical records [EMR] system).<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Once the physical examination has been completed, the patient is diagnosed by the provider and treatment is rendered.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This is entered into the clinical system and the bill for diagnosis and treatment is submitted for payment.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>What UMR now performs is an interface either with the Practice Office Management Information System’s (POMIS) Clinical System or Claims Processing System for the Diagnosis and Treatment codes.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This is what UMR calls the “back-end” of the healthcare system.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>What distinguishes UMR from another EMR or clinical solution is that the UMR database is not a clinical depository of all the clinical information, but instead provides <B>an index of the clinical information into a Review of Systems where it is categorized, counted, and dated from an initial diagnosis to one that is on-going or fully treated</B>.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This patient may go to several different providers and the clinician will not know if this disease is acute or chronic.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR solves this dilemma.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR transmits this information to the attending provider to help analyze the problem more effectively.<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">UMR is the “front-end” and “back-end” of any healthcare provider system in that UMR<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>provides abstract information in a concise fashion which allows it to communicate with a POMIS system, and has the capability to update the initial entry into the system.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR can be compared to a "Medical Table of Contents or Index" of an individual's healthcare records, which makes it most manageable for today’s managed care and utilization review.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR allows for measuring one's healthcare in an intelligent fashion which reduces duplication and triage time.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">There is another major dilemma.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>How does the patient play a role in their healthcare management? <O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">In this regard, UMR has taken a totally unique approach to healthcare.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR has the capability of working with other less complete solutions in the medical records industry allowing them to index and file these encounters for future references.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Healthcare delivery systems have in essence taken the hand written notes of the doctors and nurses and computerized them, which makes it easier to read and understand.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>However, when <SPAN style="BACKGROUND-ATTACHMENT: scroll; BACKGROUND-REPEAT: repeat; BACKGROUND-POSITION: 0% 50%; mso-spacerun: yes; mso-highlight: yellow">&nbsp;</SPAN>you add one clinical encounter after the next, these clinical notes become unorganized and are therefore not easily accessible.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>How does one organize these notes for use by other systems for which a patient may have encounters?<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR provides the necessary portability of the patient’s record from provider to provider.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This portability, coupled with a user-friendliness, for either a computer or “computer-less system” (which can be as easy as dialing 1-2-3 on the facsimile machine), that allows for the first time ever, the patient's interaction<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>with their own healthcare record.<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN><O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">UMR is a patient oriented healthcare solution that allows an individual to globally receive managed care and be treated uniformly in any healthcare setting.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>A healthcare record from a clinical system cannot be streamlined in a routine or emergency basis, and provide the managed care facility with notification for cost containment.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR addresses this problem as well.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>For example, when a patient gets injured and goes to any Emergency Room, what normally happens is that a history is obtained that is time consuming and error prone.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The healthcare system of today does not allow information to be passed directly to the Emergency Room and notify any Managed Care provider in real-time fashion.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>And, even if it could, what kind of information would be transmitted?<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>A clinical record of 10 pages, from 5 different providers?<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>No healthcare provider would waste precious time reviewing this information.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>More importantly, how would they receive this information?<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR, via the Internet, by facsimile, phone and pager has answered this dilemma.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>In this real-time setting, the Emergency Room doctor would have the UMR abstract and the primary care physician would immediately know of the emergency for real-time second opinion.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>In today's setting, the Emergency Room will tell the patient to follow-up with their doctor upon leaving the Emergency Room.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Most patients do not!<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Our system will allow the doctor to better manage the patient in a real-time fashion and thus be able to provide better quality of care. <O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal>&nbsp;<O:P> </O:P></P>
<H2><A name=prod_ben>Product Benefits</A></H2>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal>&nbsp;<O:P> </O:P></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">The Universal Medical Records has been developed by medical and data processing professionals to streamline the current inefficient process for establishing and updating an individual's medical history.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>UMR addresses three major areas of concern to the patient, the employer, the insurer, the government and the medical community: <O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-INDENT: -0.25in; TEXT-AUTOSPACE: ; MARGIN-LEFT: 1in; mso-list: l3 level1 lfo14; tab-stops: list 1.0in; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-SIZE: 10pt; mso-bidi-font-size: 12.0pt">●<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial">Proper Medical Care <O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-INDENT: -0.25in; TEXT-AUTOSPACE: ; MARGIN-LEFT: 1in; mso-list: l3 level1 lfo14; tab-stops: list 1.0in; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-SIZE: 10pt; mso-bidi-font-size: 12.0pt">●<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial">Cost Containment <O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-INDENT: -0.25in; TEXT-AUTOSPACE: ; MARGIN-LEFT: 1in; mso-list: l3 level1 lfo14; tab-stops: list 1.0in; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-SIZE: 10pt; mso-bidi-font-size: 12.0pt">●<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial">Malpractice Reduction <O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">&nbsp;<O:P> </O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; LINE-HEIGHT: 12pt; TEXT-AUTOSPACE: ; mso-layout-grid-align: none" class=MsoNormal><SPAN style="FONT-FAMILY: Arial">The benefits of integrating our solution with the expertise and nationwide distribution of various providers of medical records solutions are magnified tremendously.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>I would love the opportunity to arrange a time for you to visit our website <A href="http://www.universalmedicalrecord.com/">http://www.universalmedicalrecord.com/</A> so you can see for yourself, the benefits we have discussed above.</SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">Competition.<SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></B><SPAN style="FONT-FAMILY: Arial">There are five primary products and services that compete with Universal Medical Records™: LifeCall, Medic Alert, Life Card, Smart Cards and Electronic Medical Records.</SPAN></SPAN></P>
<P class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">Life Call</SPAN></B><SPAN style="FONT-FAMILY: Arial"> was designed for people who stay at home and in the case of medical emergency they would press a button around their neck to summon for help.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The advantages to this product are that calls for help are automatic with the push of a button and the resulting response provides medical assistance.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>On the negative side the user must be in his/her home to operate.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>It has <B><U>no on-going medical record</U></B> capability and it is expensive to maintain.</SPAN></SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">Medic Alert</SPAN></B><SPAN style="FONT-FAMILY: Arial"> is intended for those individuals who have a medical problem in which they are required to wear an I.D. bracelet for identification purposes.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This product is well-known, inexpensive, provides medical assistance and is known on a worldwide basis.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>There, however, is <B><U>no on-going medical record</U></B>, no confidentiality and some hesitancy for an individual to wear a "negative label" tag.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>There is no payment plan for the provider.</SPAN></SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">LifeCard</SPAN></B><SPAN style="FONT-FAMILY: Arial"> is a credit card with the microfiche of the medical record.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>There are several credit card companies that house a microfiche medical record permanently placed on the credit card.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This product is inexpensive and provides a payment plan for the provider.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>It, however, needs to be read by a microfiche terminal and it is difficult and expensive to update.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>There is <B><U>no on-going medical record</U></B> and if the card is lost the client may lose his/her medical confidentiality by public exposure.</SPAN></SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">Smart Cards</SPAN></B><SPAN style="FONT-FAMILY: Arial"> were designed for mobile storage capacity, identification and integrity of confidentiality.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>There are numerous types of Smart Cards: Optical, Barcoding, Magnetic Strip, Laser, Microchip, etc.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>This product is relatively expensive to implement given<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>its restricted use.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>It needs to be read by an individualized terminal and it is difficult and expensive to update. It has no telecommunications interface.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>There is <B><U>no on-going medical record</U></B> and if the card is lost the client may lose his/her entire medical record <B><U>forever</U></B>.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Does not provide globalization of health care.</SPAN></SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial">Electronic Medical Records</SPAN></B><SPAN style="FONT-FAMILY: Arial"> consists of a variety of interactive software modules which collectively integrate clinical, management and financial applications to provide data from the medical record of a single patient and single health care provider(s).<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>These electronic medical records are restricted to the health care provider's office and/or facility, providing no telecommunications interface.<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>There is <B><U>no on-going medical record</U></B> and the patient cannot accessed.</SPAN></SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>These five products and services have the capability of interfacing with UMR on a different platform with the use of computer technology.<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>UMR is the first product of its kind to offer these kinds of services directly on-line at the health care proivders officer(s).</SPAN></P>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN class=initialstyle><B><SPAN style="FONT-FAMILY: Arial"><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></U>&nbsp;<SPAN style="mso-spacerun: yes">&nbsp;</SPAN></SPAN></P>
<P class=defaulttext><SPAN style="FONT-FAMILY: Arial; mso-spacerun: yes" class=initialstyle>&nbsp;</SPAN></P>
<H2><A name=employer></A><SPAN class=initialstyle>Employer’s Wellness Tracking System</SPAN></H2>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l8 level1 lfo4; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Tracks daily health care provider activity of employee.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l8 level1 lfo4; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Daily log activity.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l8 level1 lfo4; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Immediate notification system.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l8 level1 lfo4; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Integrates health care record of employee for: &nbsp;</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 1in; mso-list: l8 level2 lfo4; tab-stops: list 1.0in" class=defaulttext><SPAN style="FONT-FAMILY: 'Courier New'; mso-bidi-font-family: 'Arial Unicode MS'">o<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Worker’s Compensation</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 1in; mso-list: l8 level2 lfo4; tab-stops: list 1.0in" class=defaulttext><SPAN style="FONT-FAMILY: 'Courier New'; mso-bidi-font-family: 'Arial Unicode MS'">o<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Disability Insurance</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 1in; mso-list: l8 level2 lfo4; tab-stops: list 1.0in" class=defaulttext><SPAN style="FONT-FAMILY: 'Courier New'; mso-bidi-font-family: 'Arial Unicode MS'">o<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Health Insurance</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 1in; mso-list: l8 level2 lfo4; tab-stops: list 1.0in" class=defaulttext><SPAN style="FONT-FAMILY: 'Courier New'; mso-bidi-font-family: 'Arial Unicode MS'">o<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Life Insurance</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 1in; mso-list: l8 level2 lfo4; tab-stops: list 1.0in" class=defaulttext><SPAN style="FONT-FAMILY: 'Courier New'; mso-bidi-font-family: 'Arial Unicode MS'">o<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Key Man Life Insurance</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 1in; mso-list: l8 level2 lfo4; tab-stops: list 1.0in" class=defaulttext><SPAN style="FONT-FAMILY: 'Courier New'; mso-bidi-font-family: 'Arial Unicode MS'">o<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Property &amp; Casualty</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 1in; mso-list: l8 level2 lfo4; tab-stops: list 1.0in" class=defaulttext><SPAN style="FONT-FAMILY: 'Courier New'; mso-bidi-font-family: 'Arial Unicode MS'">o<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Malpractice Insurance</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 1in; mso-list: l8 level2 lfo4; tab-stops: list 1.0in" class=defaulttext><SPAN style="FONT-FAMILY: 'Courier New'; mso-bidi-font-family: 'Arial Unicode MS'">o<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Product Liability</SPAN></P>
<P style="TEXT-ALIGN: center; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l1 level1 lfo5; tab-stops: list .5in" class=defaulttext align=center><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN>&nbsp;<O:P> </O:P></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l1 level1 lfo5; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Provides a benefit to the employee while emphasizing managed health care.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l1 level1 lfo5; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>User Friendly - accessed via any touch-tone phone. &nbsp;</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l1 level1 lfo5; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Removes violations regarding the Americans With Disability Act.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l1 level1 lfo5; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Provides a tool for employees to better understand their health care needs.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l1 level1 lfo5; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Interfaces to Industrial Security Monitoring Central Station for date and time<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>stamp for handling of employee emergencies for notification and documentation.</SPAN></P>
<P style="TEXT-ALIGN: center" class=defaulttext align=center><SPAN style="FONT-FAMILY: Arial" class=initialstyle>&nbsp; &nbsp;</SPAN></P>
<H2><A name=payor></A><SPAN class=initialstyle>BENEFITS TO PAYOR OR INSURER</SPAN></H2>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Contributes to reducing frivolous law suits with current and accurate information.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Reduces payouts for redundant tests and procedures.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Can be used for an insurance company promotion for<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>expanding enrollment.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Provides for a single source record and documentation of enrollees medical history and inventory.</SPAN></P>
<P style="TEXT-INDENT: 6pt" class=defaulttext>&nbsp;<O:P> </O:P></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Supports a medico and medicolegal discovery service saving court and legal costs.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Allows insurers to effectively process claims worldwide.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Enhances collection and analysis of medical data for establishing trends and actuarial projections.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Allows immediate retrieval of institutions' archived patients' medical records to improve handling&nbsp; of malpractice claims based upon inappropriate use of medical records.&nbsp;<SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="mso-spacerun: yes">&nbsp;</SPAN></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l2 level1 lfo6; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Reduces liability through confidentiality and integrity of records.&nbsp;&nbsp; &nbsp;</SPAN></P>
<P class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>&nbsp;</SPAN></P>
<H2><A name=employ></A><SPAN class=initialstyle>BENEFITS TO EMPLOYER</SPAN></H2>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l9 level1 lfo7; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Enables employers to comply with the Requirements of Title I of the Americans With Disabilities Act (ADA).</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l9 level1 lfo7; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Encourages employers to offer the same health care record to their employees as a company benefit.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l9 level1 lfo7; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Allows company to comply with the requirements of the Occupational Safety and Health<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Act (OSHA) that regulates workplace incurred diseases and injuries.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l9 level1 lfo7; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Permits employers to track chronic complaints and claims to detect fraudulent abuse.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l9 level1 lfo7; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Assists employers in processing Worker's Compensation applications.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l9 level1 lfo7; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Simplifies employer record keeping for compliance to the Environmental&nbsp; Protection Act (EPA) long-term record maintenance for employees working in hazardous industries.</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l9 level1 lfo7; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Facilitates Human Resources functions in managing employee healthcare. &nbsp;</SPAN></P>
<H2><A name=member></A><SPAN class=initialstyle>BENEFITS TO ENROLLED MEMBER</SPAN></H2>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l12 level1 lfo8; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Allows efficient recording, updating, reviewing, and retrieving medical history and inventory data such as immunizations, medications and treatments that may be prescribed by the attending physician in the office, hospital or other health care facilities.<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>Filling out a different medical form for druggists, hospitals, labs, clubs, and teams, remembering medical histories and returning to the doctor each time is no longer necessary.</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l12 level1 lfo8; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Eliminates duplicate and sometimes conflicting information and forms for different purposes such as school, work, camp, athletics, trips or other uses.</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l12 level1 lfo8; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Achieves a piece of mind that such information is always available even in times&nbsp;<SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>of emergency or when filling out forms or tax statements for reimbursement or deductions.</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l12 level1 lfo8; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol" class=initialstyle>·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN class=initialstyle><SPAN style="FONT-FAMILY: Arial">Provides a sense of security to know that very personal information is available to only those that require emergency access to it via pre-established protocol or to those designated by the member. </SPAN><O:P></O:P></SPAN></P>
<P style="TEXT-ALIGN: justify; MARGIN-LEFT: 0.25in" class=defaulttext>&nbsp;<O:P> </O:P></P>
<H2><A name=licensed></A><SPAN class=initialstyle>BENEFITS TO LICENSED HEALTH CARE PROVIDER OR PROFESSIONAL</SPAN></H2>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l5 level1 lfo9; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Accesses reliable information immediately in case of emergency in the home, physician's office, hospital or other health care facilities.</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l5 level1 lfo9; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Reduces chance of improper care and exposure to malpractice cases.</SPAN></P>
<P style="TEXT-ALIGN: justify; TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l5 level1 lfo9; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Adds value to technology in use.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l5 level1 lfo9; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol" class=initialstyle>·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN class=initialstyle><SPAN style="FONT-FAMILY: Arial">Allows immediate updating of all relevant patient history information within a single file.&nbsp;&nbsp; </SPAN><O:P></O:P></SPAN></P>
<P style="MARGIN-LEFT: 0.25in" class=defaulttext>&nbsp;<O:P> </O:P></P>
<H2><A name=government></A><SPAN class=initialstyle>BENEFITS TO GOVERNMENT</SPAN></H2>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l6 level1 lfo10; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Facilitates healthcare utilization review.</SPAN></P>
<P style="TEXT-INDENT: 6pt" class=defaulttext>&nbsp;<O:P> </O:P></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l6 level1 lfo10; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Provides an inexpensive system to maintain and operate by all provider groups, with appropriate government backing.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l6 level1 lfo10; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Integrates the emerging technologies of the information highway with the healthcare industries for record exchange,<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>collection, retrieval and currency.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l6 level1 lfo10; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Supports national objectives for standardizing healthcare across all lines and types of providers.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l6 level1 lfo10; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Creates new health care-related industries and employment opportunities within&nbsp;<SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>them.</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l6 level1 lfo10; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol" class=initialstyle>·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN class=initialstyle><SPAN style="FONT-FAMILY: Arial">Provides a service with international applicability, generated by anonymous records for risk analysis and financial projections. </SPAN><O:P></O:P></SPAN></P>
<P style="MARGIN-LEFT: 0.25in" class=defaulttext>&nbsp;<O:P> </O:P></P>
<H2><A name=hr></A><SPAN class=initialstyle>HUMAN RESOURCE COST REDUCTION</SPAN></H2>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>All US companies and corporations with 15 or more employees must comply with the requirements defined in Public Law 101-336: The Americans with Disability Act.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>One of these requirements is that the medical condition or history of the employee "shall be collected and maintained on separate forms and in separate medical files and be treated as a confidential medical record".<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>It should be emphasized that this requirement is not limited to disabled individuals or those with a special condition: it applies to <U>all</U> employees and failure to comply could subject the employer to violation citations and applicable fines.</SPAN></P>
<P class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Furthermore, the referenced act does not define a federally- approved standard for this employee health profile, but the UMR format <U>Standard Guide for Providing Essential Data Needed in Advance for Prehospital Emergency Medical Services</U> has been developed in conjunction with the standard by the American Standard for Testing and Materials (ASTM) and approved on October 10, 1995.</SPAN></P>
<P class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>&nbsp; &nbsp;</SPAN></P>
<H2><A name=samp></A><SPAN class=initialstyle>UMR SAMPLE RECORD PRINTOUT</SPAN></H2>
<P style="TEXT-ALIGN: justify" class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Please <A href="client_access.htm">sign up</A>. After you sign up you will be contacted by a UMR representative.</SPAN> </P>
<H2><A name=med></A><SPAN class=initialstyle>MEDICAL RECORD ANALYZER</SPAN><SPAN style="FONT-FAMILY: Symbol">ä</SPAN><SPAN class=initialstyle> BUREAU RELATED BUSINESS APPLICATIONS</SPAN></H2>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l13 level1 lfo11; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Automated medical records analysis for expediting legal reviews; expert witness reviews; auditing medical bills</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l13 level1 lfo11; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Identifying Medicare/Medicaid fraud and abuse</SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN-LEFT: 0.5in; mso-list: l13 level1 lfo11; tab-stops: list .5in" class=defaulttext><SPAN style="FONT-FAMILY: Symbol">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><SPAN style="FONT-FAMILY: Arial" class=initialstyle>Compliance with federal, state and industry sanctioned quality control regulations and programs</SPAN></P>
<P class=defaulttext><SPAN style="FONT-FAMILY: Arial" class=initialstyle>With the power of the UMR Medical Record Analyzer Bureau the tedious time consuming task of analyzing, organizing and correlating the scrambled “Babylonian” medical coding jargon can be processed in a cost effective and timely manner for getting the desired business results.</SPAN><!--msnavigation--></P></B></SPAN></div></td>
      </tr>
    </table>
                                    </td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td bgcolor="#0b7ca9" class="bot-bg"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td class="bottom_menu"><a href="Default.aspx">Home Page</a>  |  
            <a href="AboutUs1.aspx">About Us</a>  |  <a href="Products.aspx">Products and Services</a>  |  
            <a href="Client1.aspx">Client Access</a>  |  <a href="Contact.aspx">Contact Us</a>   |  
            <a href="References.aspx">References</a>  |  <a href="#">.....</a></td>
      </tr>
      <tr>
        <td class="bottom_addr">© 2011-2013 UMR Holdings International Corp. All Rights Reserved<br>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>
</tr>
</table>

    </form>
</div>
</body>
</html>
