//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMRPublicBO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalJob
    {
        public long ExternalJobID { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public int ReqJobOpeningId { get; set; }
    }
}
