//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMRPublicBO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobContent()
        {
            this.UserJobs = new HashSet<UserJob>();
        }
    
        public int JobContentId { get; set; }
        public string JobTitle { get; set; }
        public string NoOfVacancies { get; set; }
        public string JobDescription { get; set; }
        public string JobNature { get; set; }
        public string EducationalRequirements { get; set; }
        public string ExperienceRequirements { get; set; }
        public string AdditionalJobRequirements { get; set; }
        public string JobLocation { get; set; }
        public string SalaryRange { get; set; }
        public string OtherBenefits { get; set; }
        public string EmailCV { get; set; }
        public string SpecialInstruction { get; set; }
        public string ApplicationDeadline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserJob> UserJobs { get; set; }
    }
}
