//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMRPublic.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UMRJobsEntities : DbContext
    {
        public UMRJobsEntities()
            : base("name=UMRJobsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<JobContent> JobContents { get; set; }
        public DbSet<UserCredential> UserCredentials { get; set; }
        public DbSet<UserJob> UserJobs { get; set; }
    }
}
