//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMRPublic.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserJob
    {
        public int UserJobId { get; set; }
        public int UserCredentialId { get; set; }
        public int JobContenId { get; set; }
    
        public virtual JobContent JobContent { get; set; }
        public virtual UserCredential UserCredential { get; set; }
    }
}
