//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMRPublic.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredential
    {
        public UserCredential()
        {
            this.UserJobs = new HashSet<UserJob>();
        }
    
        public int UserCredentialId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
    
        public virtual ICollection<UserJob> UserJobs { get; set; }
    }
}
